### ISSUE TITLE
Bug while assigning

### ISSUE THREAD

**Issue by swapagarwal** [coala/corobo#302] opened 2017-10-17 14:49 UTC
In Gitter, the following conversation took place:
```
@newbazz corobo assign coala/coala#3259
@co-robo Congratulations! You've been assigned to the issue. :tada:
```
On the issue page, the correspondence contains:
```
newbazz unassigned jrrickerson
co-robo assigned newbazz
```
I believe the unassignment by newbazz is a bug in corobo, and needs to be investigated.

**Comment by Makman2** [comment] 2017-10-18 00:06
That shouldn't happen indeed.
CC @meetmangukiya

**Comment by meetmangukiya** [comment] 2017-10-18 07:42
> newbazz unassigned jrrickerson

This seems disastrous :/ This is not even corobo unassigning and I don't think he is a maintainer either

**Comment by prnvdixit** [comment] 2017-10-18 07:47
@meetmangukiya No, he's not actually. Also, I asked on gitter chat if he did something else other than assigning himself the issue (to reproduce the bug again) - He replied in negation. [October 17, 2017 8:25 PM](https://gitter.im/coala/coala?at=59e619f45c40c1ba79b0ad36)

**Comment by meetmangukiya** [comment] 2017-10-18 08:09
I don't think this is a bug in corobo, also if you see the time of activities, then one may notice that the unassignment and assignment differs by an hour. Also, I think @newbazz might've mistakenly unassigned himself(if that's even possible!) Maybe there has been some permission changes recently in github

For testing purposes, can any non-maintainer(@swapagarwal or @prnvdixit) try to unassign me from this issue. Is it possible for you guys?

**Comment by meetmangukiya** [comment] 2017-10-18 08:11
One more piece of information: @newbazz is only part of newcomers team

**Comment by prnvdixit** [comment] 2017-10-18 08:35
@meetmangukiya 
> Also, I think @newbazz might've mistakenly unassigned himself(if that's even possible!)
Yeah, you can unassign yourself always 😄
> For testing purposes, can any non-maintainer(@swapagarwal or @prnvdixit) try to unassign me from this issue. Is it possible for you guys?
I tried - It doesn't let me unassign you.. 👍

**Comment by meetmangukiya** [comment] 2017-10-18 08:38
> Yeah, you can unassign yourself always 😄

I meant, mistakenly unassign the previous assignee, but you don't seem to be able to unassign me. It is quite mysterious how he could've unassigned someone from the issue.

**Comment by prnvdixit** [comment] 2017-10-18 08:40
@meetmangukiya BTW I can't see any difference in times between ```assignment``` and ```unassignment``` (```19 Hours ago``` for both) - Is it there? (Maybe difference of some minutes?)

**Comment by swapagarwal** [comment] 2017-10-18 13:14
@meetmangukiya I can't seem to unassign you either! 🤔

**Comment by meetmangukiya** [comment] 2017-11-03 08:27
Not able to reproduce this issue, hence, closing it.

**Closed by meetmangukiya** 2017-11-03 08:27 UTC
Labels: bug, importance/high, status/cannot reproduce
