### ISSUE TITLE
Add option to close an issue

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#344] opened 2017-11-22 09:27 UTC
https://gitlab.com/coala/cobot/issues/30

**Comment by Vamshi99** [comment] 2017-11-28 18:37
@jayvdb Can we limit this command to devs and maintainers?

**Comment by Vamshi99** [comment] 2017-11-28 18:37
@jayvdb Can we limit this command to devs and maintainers?

**Comment by Makman2** [comment] 2017-11-28 21:40
Actually I don't want to give developers the control to close issues, I think maintainers should take a look and decide whether an issue is solved/valid/etc, because they usually have a better overview of the situation / know where to get the relevant information.

As maintainers are already able to close issues/PRs to their likings directly via GitHub UI, I would vote to tag this issue as `invalid`.

@jayvdb you are more or less my opinion if I've read correctly on the GitLab issue. But the issue is quite old, maybe it has changed? ;)

**Comment by meetmangukiya** [comment] 2017-11-29 02:46
IMO if an issue is opened through corobo then the only person that should be able to close it with corobo should be the original issue author

**Comment by Makman2** [comment] 2017-11-29 11:56
> IMO if an issue is opened through corobo then the only person that should be able to close it with corobo should be the original issue author

Even in that case I'm not always sure. Sometimes they might close them because they think they filed them "badly" (e.g. typo) instead of editing them (although only maintainers can do this), or because of other reasons.

**Comment by AkshJain99** [comment] 2019-02-10 08:53
@jayvdb or @Makman2  is this issue still need enhancement? I mean do we need an option to close issue because ithink @Makman2 is saying absolutely true that rights for closing any issue should be only with maintainers

**Comment by sladyn98** [comment] 2019-02-10 16:21
@AkshJain99 Yeah I think the command should only cater to maintainers or developers since the right to close an issue should rest with the developers.

**Comment by AkshJain99** [comment] 2019-02-10 16:23
do you think that developer should be given rights to close issue?

**Comment by sladyn98** [comment] 2019-02-10 16:33
@AkshJain99 No they should not be given be given rights they should only be available to maintainers, because they are the ones to merge an issue so they should be the ones to close it as well.

**Comment by AkshJain99** [comment] 2019-02-10 16:35
yes i thought the same :+1:

**Comment by Makman2** [comment] 2019-04-15 17:13
It's decided: we won't implement something in this direction without a major reason.

**Closed by Makman2** 2019-04-15 17:13 UTC
Labels: area/labhub, enhancement, status/needs design, wontfix
