### ISSUE TITLE
[GSoC '18] Add ability to ban from all gitter rooms at once 

### ISSUE THREAD

**Issue by nvzard** [coala/corobo#549] opened 2018-06-07 09:13 UTC

**Comment by meetmangukiya** [comment] 2018-06-12 14:52
Duplicate of https://github.com/coala/corobo/issues/462.
@nvzard it seems @Vamshi99 already has most of the work done, ban as well as unban.

**Closed** 2018-06-14 14:32 UTC
Labels: area/ci, enhancement

**Comment by jayvdb** [comment] 2018-07-09 09:38
Grrr... We should not have GSoC specific issues.

This is a duplicate of https://github.com/coala/corobo/issues/462
