### ISSUE TITLE
searchdocs_test: change `http://` links to 'https://`

### ISSUE THREAD

**Issue by nvzard** [coala/corobo#579] opened 2018-07-06 08:00 UTC
Change `http` to `https`
https://github.com/coala/corobo/blob/de4fbaff1bd227d078f15e8221ea4941fdcf4450/tests/searchdocs_test.py#L7

difficulty/newcomer

**Comment by jayvdb** [comment] 2018-07-12 13:52
Invite sent.

This issue was very badly written.

The cause of the http link is https://github.com/coala/corobo/blob/master/plugins/searchdocs.py , which uses the constant in https://github.com/coala/corobo/blob/master/plugins/constants.py

**Comment by vaibhav9619** [comment] 2018-08-01 20:33
Please assign me this issue

**Comment by bhavya17037** [comment] 2018-08-05 08:29
Hi, can somebody assign me to this issue? This would be my first PR to Coala :)

**Comment by jayvdb** [comment] 2018-08-11 01:46
ping @ankitb073 , your PR still need work

**Comment by jayvdb** [comment] 2018-08-11 01:47
@vaibhav9619, if you finish your PR first, I will re-assign this issue to you.  Be quick.

**Comment by jayvdb** [comment] 2018-08-13 07:01
@vaibhav9619 created https://github.com/coala/corobo/pull/614 which is a duplicate of https://github.com/coala/corobo/pull/595 , so they have been removed from @coala .

**Comment by bkhanale** [comment] 2018-10-18 18:17
@jayvdb Can I take this up, I'll fix it quickly. Besides there are not so many newcomer issues left :sweat_smile:

**Closed** 2018-10-25 19:56 UTC
Labels: area/tests, difficulty/newcomer
